import type { Messages } from '../types'

export const en: Messages = {
  brandTag: 'Hold to Reveal PNG Maker',
  nav: {
    home: 'Home',
    how: 'How it works',
    examples: 'Examples',
    faq: 'FAQ',
    privacy: 'Privacy',
  },
  footer: {
    localOnly: 'Images stay on your device',
    viralLink: 'Viral hold-to-reveal post',
  },
  home: {
    h1: 'HoldReveal — Click to Reveal / Hold to Reveal PNG Generator for X',
    lead: 'Upload two images and export a transparent PNG that looks like A on a white timeline and B on a black lightbox—built for X (Twitter). All processing runs in your browser; nothing is uploaded.',
    warn: 'Posting from the X mobile app may convert PNG to JPEG and kill transparency. Upload from the X website (x.com) on desktop. Dark-mode timelines can spoil the effect early.',
    warnLink: 'How it works',
    toolTitle: 'Maker',
    loadDemo: 'Try demo images',
    slotA: 'A · Timeline look',
    slotAHint: 'What you want on white background',
    slotB: 'B · Opened look',
    slotBHint: 'What you want on black background',
    mode: 'Mode',
    modeLuma: 'Luma (recommended for art)',
    modeRgb: 'RGB (strong color differences)',
    strength: 'Strength',
    export: 'Export',
    exportPng8: 'PNG-8 (light, recommended)',
    exportRgba: 'PNG-32 RGBA',
    recompose: 'Recompose',
    composing: 'Composing…',
    download: 'Download PNG',
    needTwo: 'Please choose both image A and image B',
    composeFail: 'Compose failed',
    copyFail: 'Copy failed',
    demoFail: 'Failed to load demo images',
    previewBar: 'Preview (simulates X backgrounds)',
    tabWhite: 'White · TL',
    tabBlack: 'Black · Open',
    tabCard: 'Card gray',
    previewEmpty: 'Pick A and B to preview here',
    captionsTitle: 'Post captions',
    copy: 'Copy',
    copied: 'Copied',
    drop: 'Click / drop',
    clear: 'Clear',
    resultsTitle: 'Example results',
    resultsLead:
      'See how the same transparent PNG shifts between white (timeline) and black (lightbox). Toggle white/black on each card.',
    resultsMore: 'View all →',
    caseViralTitle: 'Viral “hold to reveal?” art',
    caseViralDesc:
      'A high-engagement dual-look illustration. White ⇄ black shows different states.',
    caseViralCredit: 'Rights belong to the original creator · educational preview',
    caseViralLink: 'Original post',
    caseDualTitle: 'Background-difference sample',
    caseDualDesc:
      'How alpha reacts to background color. Make the same class of PNG in the maker above.',
    caseDualCredit: 'Reference sample · educational',
    caseDemoTitle: 'HoldReveal demo compose',
    caseDemoDesc:
      'Generated by our algorithm. Use “Try demo images” to load the same A/B pair.',
    caseDemoCredit: 'Site-generated demo',
    caseDemoTry: 'Load this demo',
    sideWhite: 'White · timeline-style',
    sideBlack: 'Black · lightbox-style',
    guideTitle: 'How to make a click-to-reveal PNG for X',
    guideP1:
      '“Hold to reveal” / “click to reveal” / “tap to change illustration” is not animation—it’s one transparent PNG that reads differently on X’s light timeline vs dark expanded view. Not the same as “Tap the Post” grids or “load in 4K”.',
    guideSteps: [
      'Prepare A: the look for a light/white timeline background',
      'Prepare B: the look for a dark/black opened background',
      'Compose in the maker and check white/black previews',
      'Download PNG and post from the X website (not the app)',
    ],
    guideP2: 'Math, PNG-8 tips, and disambiguation live on the',
    guideHowLink: 'how-it-works page',
    tipsTitle: 'Posting tips',
    tips: [
      'App upload may strip transparency → prefer X Web',
      'Dark theme can reveal B too early',
      'Align A/B composition; keep contrast where the change should land',
    ],
    relatedTitle: 'Related',
    faqTitle: 'FAQ (highlights)',
    faqMore: 'More FAQ →',
    faqItems: [
      {
        q: 'Why does the picture change?',
        a: 'Transparent PNG + white timeline vs black lightbox on X. Not APNG/GIF animation.',
      },
      {
        q: 'Is this “tap and hold for 4K”?',
        a: 'No. That is a different trend. This is dual-look transparent PNG.',
      },
      {
        q: 'It doesn’t change well',
        a: 'Align A/B, boost contrast, try strength/RGB mode, re-upload via Web.',
      },
    ],
    captions: [
      'Hold to reveal 👀',
      'Click to reveal',
      'Tap to change illustration',
      'White TL / black open',
    ],
  },
  how: {
    title:
      'How Click-to-Reveal PNGs Work on X | Hold to Reveal | HoldReveal',
    description:
      'How transparent PNGs show different art on white vs black backgrounds on X/Twitter. Alpha math, PNG-8, not 4K hold, not Tap the Post.',
    h1: 'How hold-to-reveal / click-to-reveal works',
    intro:
      'This is not video or APNG. One transparent PNG looks like image A on a light timeline and image B on a dark lightbox because of alpha compositing against different backgrounds.',
    ctaMake: 'Open the maker',
    ctaExamples: 'See examples',
    s1: '1. UI background difference',
    s1p: 'On many light themes:',
    s1li1: 'Timeline: bright / near-white card background',
    s1li2: 'Expanded image: dark / near-black background',
    s1p2:
      'Near-transparent pixels let the background show through—so white “hides” some strokes and black “reveals” others.',
    s1p3:
      'Captions like “hold to reveal” are engagement copy; the real switch is open/lightbox background, not a special gesture API.',
    s2: '2. The formula (inverse alpha)',
    s2p: 'Display color ≈ pixel × α + background × (1 − α).',
    s2p2:
      'If W is the white-bg look and B the black-bg look: α = clamp(1 − W + B), C = B / α.',
    s2p3:
      'HoldReveal solves α and color per pixel from your A/B inputs (luma or RGB mode).',
    s3: '3. Why PNG-8',
    s3p:
      'Large RGBA uploads can be recompressed on X. Indexed PNG-8 often keeps transparency more reliably.',
    s4: '4. Not those other trends',
    s4li1: 'HoldReveal: dual vision via transparency + white/black UI',
    s4li2: '“Load in 4K” / “Tap the Post” grids: different mechanisms',
    s5: '5. Tips that work',
    s5li: [
      'Match composition between A and B',
      'Strong contrast where the reveal should happen',
      'Post PNG from x.com on desktop',
      'Dark mode may spoil the timeline look',
    ],
    s6: '6. Steps in HoldReveal',
    s6ol: [
      'Upload A (white-bg look)',
      'Upload B (black-bg look)',
      'Preview white/black; tweak strength/mode',
      'Download PNG → post on X Web',
    ],
    ctaNow: 'Make one now',
    ctaFaq: 'Read FAQ',
  },
  examples: {
    title: 'Examples | Click to Reveal PNG for X | HoldReveal',
    description:
      'Hold to reveal / click to reveal illustration examples with white and black previews.',
    h1: 'Example gallery',
    lead: 'Toggle white ⇄ black to see background-difference dual PNGs. Then make your own in the free browser maker.',
    ctaMake: 'Make yours',
    ctaHow: 'Read the science',
    disclaimer:
      'Third-party art remains with rights holders. Shown for education only—no redistribution.',
    cases: [
      {
        id: 'viral',
        title: 'Viral hold-to-reveal post',
        desc: 'High-engagement dual-look illustration example from July 2026.',
        credit: 'Rights with original creator · educational preview',
        sourceLabel: 'View original post',
      },
      {
        id: 'dual',
        title: 'Dual PNG sample',
        desc: 'Background-reactive transparent PNG look you can recreate.',
        credit: 'Reference sample',
        sourceLabel: 'How it works',
      },
      {
        id: 'demo',
        title: 'HoldReveal demo',
        desc: 'Composed by this site’s algorithm.',
        credit: 'Site-generated',
        sourceLabel: 'Make the same way',
      },
    ],
  },
  faq: {
    title: 'FAQ | Hold to Reveal PNG Maker | HoldReveal',
    description:
      'FAQ for click-to-reveal / hold-to-reveal dual PNGs on X: posting, dark mode, PNG-8, privacy.',
    h1: 'FAQ',
    lead: 'Questions about HoldReveal, the dual-image transparent PNG maker for X.',
    homeLink: 'Home',
    ctaMake: 'To the maker',
    ctaHow: 'How it works',
    items: [
      {
        q: 'Why does it change?',
        a: 'Alpha PNG + white timeline vs black lightbox. Not animation.',
      },
      {
        q: 'Same as 4K long-press?',
        a: 'No—different trend. This is dual-look transparency.',
      },
      {
        q: 'Can I post from the app?',
        a: 'Risky: apps often flatten PNG to JPEG. Prefer X Web.',
      },
      {
        q: 'Dark mode issues?',
        a: 'Yes—timeline may already look “opened”. Best on light theme.',
      },
      {
        q: 'Do you upload my images?',
        a: 'No. Everything runs locally in the browser.',
      },
      {
        q: 'Reveal looks weak',
        a: 'Align A/B, raise contrast, try strength or RGB mode.',
      },
      {
        q: 'PNG-8 vs PNG-32?',
        a: 'PNG-8 is smaller and often keeps alpha better on X; use RGBA if colors posterize.',
      },
      {
        q: 'Commercial use?',
        a: 'Tool is free; rights follow your source assets.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy | HoldReveal',
    description:
      'HoldReveal privacy: images processed only in your browser. Google Analytics note.',
    h1: 'Privacy Policy',
    updated: 'Last updated: 2026-07-25',
    s1: 'Image data',
    s1p1:
      'HoldReveal composes dual-vision PNGs in the browser. Your uploads never leave your device to our servers.',
    s1p2: 'Downloads are local. Closing the tab discards in-memory data.',
    s2: 'Analytics',
    s2p1:
      'We use Google Analytics 4 (G-SPFR4DJ4L4) for traffic stats. Image pixels are not sent.',
    s2p2: 'See Google’s policies and browser opt-outs.',
    s3: 'Cookies',
    s3p: 'Analytics may use cookies. No login or ad network yet.',
    s4: 'External links',
    s4p: 'Third-party sites (e.g. X) have their own policies.',
    s5: 'Contact',
    s5p: 'Contact the operator via published channels for privacy questions.',
    ctaHome: 'Back home',
  },
  seo: {
    homeTitle:
      'HoldReveal | Click to Reveal PNG Generator for X (Twitter) — Hold to Reveal',
    homeDescription:
      'Free dual-image transparent PNG maker: white timeline vs black lightbox on X. Hold to reveal / click to reveal—not Tap the Post, not 4K. 100% in-browser.',
  },
}
